---
title: "Gower_distance"
author: "Vica"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(cluster)
library(tidyverse)
```

```{r}
med <- read.csv("../Data/Med_cyano_list_20191024.csv", row.names = NULL)
med <- med %>% 
  filter(Med_border == "yes")
colnames(med)[1] <- "A/A"
med <- med %>% 
  mutate(continent = case_when(Country %in% c("Greece", "Italy", "Spain", "France", "Albania", "Montenegro", "Slovenia", "Portugal", "Bulgaria", "Croatia") ~ "Europe",
                               Country %in% c("Egypt", "Morocco", "Tunisia", "Libya", "Algeria", "Israel","Lebanon") ~ "Africa",Country == "Turkey" ~ "Asia"))

med <- med %>% 
mutate(lat_range = case_when(DD_Lat < 30 ~ "Low", DD_Lat > 30 & DD_Lat < 40 ~ "Medium",
                             DD_Lat > 40 ~ "High"))
med
```


```{r}
sample.data <- med %>% 
  filter(Order != "") %>% 
  select(Order, Currentname, Habitat, Habitat_type, Lifestyle) %>% 
  group_by(Currentname, Habitat, Habitat_type, Lifestyle) %>% 
  summarize(N = n()) %>% 
  arrange(desc(N))
sample.data
```



```{r}
gower.dissimilarity <- daisy(sample.data, metric = c("gower"))
gower.dissimilarity

gower.mat <- as.matrix(gower.dissimilarity)
gower.mat

write.table("gower.dissimilarity.csv")
```

