---
title: "heatmap"
author: "Vica"
date: "11/6/2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(plotly)
library(heatmaply)
library(RColorBrewer)
library(gplots)
library(vegan)
```

```{r}
ap <- available.packages()
"d3TreeR" %in% rownames(ap)
```



```{r}
med <- read.csv("../Data/Medcyanolist_source_20200130_yes.csv")
med <- med %>% 
  filter(Med_border == "yes")
colnames(med)[1] <- "A/A"
med <- med %>% 
  mutate(continent = case_when(Country %in% c("Greece", "Italy", "Spain", "France", "Albania", "Montenegro", "Slovenia", "Portugal", "Bulgaria", "Croatia") ~ "Europe",
                               Country %in% c("Egypt", "Morocco", "Tunisia", "Libya", "Algeria", "Israel","Lebanon") ~ "Africa",Country == "Turkey" ~ "Asia"))

med <- med %>% 
mutate(lat_range = case_when(DD_Lat < 30 ~ "Low", DD_Lat > 30 & DD_Lat < 40 ~ "Medium",
                             DD_Lat > 40 ~ "High"))
med
```


```{r}
med.toxins <- read.csv("../Data/Mediterranean_Cyanobacteria_toxins.csv")
colnames(med.toxins)[1] <- "A/A"
med.toxins
```


##HEATMAP with ggplot2-function geom_tile


```{r}
#med.heat.1 <- med.toxins %>% 
  #select(Country, Toxin) %>% 
  #group_by(Country, Toxin) %>% 
  #summarize(N = n()) 
#med.heat.1

#test <- unlist(med.heat.1$Country)

## package ggplot2-function geom_tile

#med.heat.1.country <- ggplot(med.heat.1, aes(x = Toxin, y = Country, fill = test)) + geom_tile() + 
  #scale_fill_distiller(palette = "RdGy") 
#med.heat.1.country
```


```{r}
med.heat <- med.toxins %>% 
  select(Country, Toxin) %>% 
  group_by(Country, Toxin) %>% 
  summarize(N = n_distinct("Country")) %>%  spread(Toxin, N, fill = 0) %>% column_to_rownames("Country")
med.heat <- as.matrix(med.heat)
class(med.heat)
med.heat

x <- heatmaply(med.heat, 
               dendrogram = "none", 
               scale = "column", 
               grid_color = "white", 
               grid_width = 0.00001, 
               hide_colorbar = TRUE,
               branches_lwd = 0.1,
               labCol = colnames(med.heat),
               labRow = rownames(med.heat),
               heatmap_layers = theme(axis.line = element_blank()))
x




med.heat.scale <- scale(med.heat)
med.heat.scale
map <- heatmap.2(med.heat, scale="none",col = bluered(100), trace = "none", density.info = "none")
```


##HEATMAP using package gplots Currentname-Toxin


```{r fig.height=6, fig.width=8, echo=FALSE}
med.heat.spe <- med.toxins %>% 
  select(Currentname, Country, Toxin) %>% 
  group_by(Currentname,Toxin) %>% 
  summarize(N = n_distinct("Currentname")) %>% 
  spread(Toxin, N, fill = 0) %>% 
  column_to_rownames("Currentname")
med.heat.spe <- as.matrix(med.heat.spe) ## Μετατροπή του dataframe σε matrix
#med.heat.spe


##med.heat.scale.spe <- scale(med.heat.spe) 
tiff("../Results/heatmap.2.tiff", res = 300, units = "in",  width=7, height=6)

map.spe <- heatmap.2(med.heat.spe,
                     dendrogram = "both",
                     key = TRUE,
                     #keysize = 1.5,
                     cexRow = 0.64,
                     cexCol = 0.8,
                     margins = c(6,10),
                     srtRow=0, srtCol=45, offsetRow=-0.5, offsetCol=-0.5,
                     scale="none",
                     #distfun = dist,
                     sepcolor = "white",
                     col = c("#66c2a5", "#fc8d62"),
                     lwid = c(0.8,1),
                     lhei=c(0.05, 0.2 ),
                     labRow=as.expression(lapply(rownames(med.heat.spe), function(a) bquote(italic(.(a))))),
                     sepwidth = c(1,1.5),
                     trace = "none", 
                     density.info = "none"
                     )
dev.off()
```

```{r fig.height=6, fig.width=8, echo=FALSE}
med.heat.spe <- med.toxins %>% 
  select(Currentname, Country, Toxin, Med_border) %>% 
  filter(Med_border == "yes") %>% 
  group_by(Currentname,Toxin) %>% 
  summarize(N = n_distinct("Currentname")) %>% 
  spread(Toxin, N, fill = 0) %>% 
  column_to_rownames("Currentname")
med.heat.spe <- as.matrix(med.heat.spe) ## Μετατροπή του dataframe σε matrix
#med.heat.spe


##med.heat.scale.spe <- scale(med.heat.spe) 
tiff("../Results/heatmap.test.tiff", res = 300, units = "in",  width=7, height=6)

spe_dist <- vegdist(med.heat.spe, method = "euclidean" )
spe_hclust <- hclust(spe_dist, method = "ward.D")
plot(spe_hclust)

tox_dist <- vegdist(t(med.heat.spe), method = "euclidean")
tox_hclust <- hclust(tox_dist, method ="ward.D")
plot(tox_hclust)

map.spe <- heatmap.2(med.heat.spe,
                     Rowv = as.dendrogram(spe_hclust),
                     Colv = as.dendrogram(tox_hclust),
                     dendrogram = "both",
                     key = TRUE,
                     #keysize = 1.5,
                     cexRow = 0.64,
                     cexCol = 0.8,
                     margins = c(6,10),
                     srtRow=0, srtCol=45, offsetRow=-0.5, offsetCol=-0.5,
                     scale="none",
                     #distfun = dist,
                     sepcolor = "white",
                     col = c("#66c2a5", "#fc8d62"),
                     lwid = c(0.8,1),
                     lhei=c(0.05, 0.2 ),
                     labRow=as.expression(lapply(rownames(med.heat.spe), function(a) bquote(italic(.(a))))),
                     sepwidth = c(1,1.5),
                     trace = "none", 
                     density.info = "none"
                     )
dev.off()
```



```{r fig.height=6, fig.width=7, results='hide'}
med.heat.country <- med.toxins %>% 
  select(Country, Toxin) %>% 
  group_by(Country,Toxin) %>% 
  summarize(N = n_distinct("Country")) %>% 
  spread(Toxin, N, fill = 0) %>% 
  column_to_rownames("Country")
med.heat.country <- as.matrix(med.heat.country) ## Μετατροπή του dataframe σε matrix
med.heat.country


##med.heat.scale.spe <- scale(med.heat.spe) 
png("../Results/heatmap.country.png", width=700, height=400)

map.country <- heatmap.2(med.heat.country, 
                     dendrogram = "both",
                     key = TRUE,
                     #keysize = 1.5,
                     cexRow = 1,
                     cexCol = 1,
                     margins = c(6,4),
                     srtRow=0, srtCol=45, offsetRow=-0.5, offsetCol=-0.5,
                     scale="none",
                     #distfun = dist,
                     sepcolor = "black",
                     col = c("#66c2a5", "#fc8d62"),
                     lwid = c(0.8,1),
                     lhei=c(0.05, 0.2 ),
                     sepwidth = c(1,1.5),
                     trace = "none", 
                     density.info = "none"
                     )
dev.off()
```

#Package heatmaply Country-Toxin

```{r}
med.heatmaply <- med.toxins %>% 
  select(Currentname, Country, Toxin) %>% 
  group_by(Country,Toxin) %>% 
  summarize(N = n_distinct("Country")) %>%  spread(Toxin, N, fill = 0) %>% column_to_rownames("Country")
med.heatmaply <- as.matrix(med.heatmaply)
class(med.heatmaply)
med.heatmaply

b <- heatmaply(med.heatmaply, dendrogram = "both",
               colors = viridis(n = 2, alpha = 1, begin = 0, end = 1, option = "viridis"),
               xlab = "", ylab="",
               scale = "column",
               margins = c(60,100,40,20),
               grid_color = "white",
               grid_width= 0.00001,
               titleX = FALSE,
               hide_colorbar = TRUE,
               branches_lwd = 0.1,
               label_names = c("Country", "Currentname", "Ν"),
               fontsize_row = 12, fontsize_col = 12,
               labCol = colnames(med.heatmaply),
               labRow = rownames(med.heatmaply),
               heatmap_layers = theme(axis.line = element_blank())
  
)
b
```


# Representing different toxins per habitat

```{r}
habtox <- med.toxins %>% 
  select(Habitat, Toxin) %>% 
  group_by(Habitat, Toxin) %>% 
  summarize(N = n())
habtox

habtox.plot <- ggplot(habtox, aes(x = Habitat, y = N, fill = Toxin)) + geom_bar(stat = "identity")
habtox.plot

habtox <-  as.matrix(habtox)
```


```{r}
countrytox <- med.toxins %>% 
  select(Country, Toxin) %>% 
  group_by(Country, Toxin) %>% 
  summarize(N = n())
countrytox

countrytox.plot <- ggplot(countrytox, aes(x = Country, y = N, fill = Toxin)) + geom_bar(stat = "identity")
countrytox.plot

country.plot <- ggplot(countrytox, aes(x =reorder(Country, - N), y = N)) + geom_bar(stat = "identity")
country.plot
```

