---
title: "Lifestyle"
author: "Vica"
date: "12/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(betapart)
library(tidyverse)
library(mapproj)
library(vegan)
library(stringr)
library(reshape2)
library(splitstackshape)
```


```{r}
med <- read.csv("../Data/Med_cyano_list_20191212.csv", row.names = NULL)
med <- med %>% 
  filter(Med_border == "yes")
colnames(med)[1] <- "A/A"
med <- med %>% 
  mutate(continent = case_when(Country %in% c("Greece", "Italy", "Spain", "France", "Albania", "Montenegro", "Slovenia", "Portugal", "Bulgaria", "Croatia") ~ "Europe",
                               Country %in% c("Egypt", "Morocco", "Tunisia", "Libya", "Algeria", "Israel","Lebanon") ~ "Africa",Country == "Turkey" ~ "Asia"))

med <- med %>% 
mutate(lat_range = case_when(DD_Lat < 30 ~ "Low", DD_Lat > 30 & DD_Lat < 40 ~ "Medium",
                             DD_Lat > 40 ~ "High"))
med

```



```{r}
# split column lifestyle

ls_split<- cSplit(med, "Lifestyle", "/")
ls_split


```


```{r}
ls_split_med <- ls_split %>% 
  filter(Order != "") %>% 
  select(Currentname, Lifestyle_1:Lifestyle_5) %>% 
  gather(Lifestyle_all, value, -Currentname) %>% 
  select(Currentname, value) %>%   
  drop_na %>%
  mutate(yesno = 1) %>% 
  distinct %>% 
  spread(value, yesno, fill = 0) %>% 
  column_to_rownames("Currentname")

ls_split_med

ls_split_med %>% 
  colSums()

```


```{r fig.height=50, fig.width=10}
a <- dist(ls_split_med)
b <- hclust(a, method = "ward.D2")

library(ape)
plot(as.phylo(b), cex = 0.8, label.offset = 0.25, no.margin = T)

```

