---
title: "venn_diagram"
author: "Vica"
date: "10/26/2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r}
library(tidyverse)
```


```{r}
med <- read.csv("../Data/Med_cyano_list_20191024.csv", row.names = NULL)
med <- med %>% 
  filter(Med_border == "yes")
colnames(med)[1] <- "A/A"
med <- med %>% 
  mutate(continent = case_when(Country %in% c("Greece", "Italy", "Spain", "France", "Albania", "Montenegro", "Slovenia", "Portugal", "Bulgaria", "Croatia") ~ "Europe",
                               Country %in% c("Egypt", "Morocco", "Tunisia", "Libya", "Algeria", "Israel","Lebanon") ~ "Africa",Country == "Turkey" ~ "Asia"))
```



```{r}
inter <- list()
for(i in 1:length(levels(med$Habitat))){
inter[[i]] <- intersect(filter(med, Habitat == levels(Habitat)[i])$Currentname, 
                        filter(med, Habitat == levels(Habitat)[i+1])$Currentname)
}
```


```{r}
Reduce(intersect,list(group_by(med, Habitat)$Currentname))
```

```{r}
library(RVenn)

med <- droplevels(med)

test <- split(med, med$Habitat)

test2 <- sapply(test, function(x){
  unique(x["Currentname"])
})

test3<- lapply(test2, droplevels)
test4 <- lapply(test3, as.character)
test5 <- Venn(test4)
overlaps <- overlap_pairs(test5)
test5
overlaps

capture.output(overlaps, file = "overlaps.csv")
```

```{r fig.width=12, fig.height=5}
gven <- ggvenn(test5, slice = c(3,6,8))
gven
ggsave
```

```{r}
setmap(test5)
```

# 2nd try

```{r}
# Get the combinations of names of list elements
nms <- combn( names(test3) , 2 , FUN = paste0 , collapse = "" , simplify = FALSE )

# Make the combinations of list elements
ll <- combn( test3 , 2 , simplify = FALSE )

# Intersect the list elements
out <- lapply( ll , function(x) length( intersect( x[[1]] , x[[2]] ) ) )

# Output with names
my_list <- setNames( out , nms )
my_list
```

```{r}
common.taxa <- unlist(my_list)
as.data.frame(common.taxa)
```

