---
title: "Word"
author: "Victoria Giourieva"
date: "2/19/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
```{r}
knitr::opts_chunk$set(echo = TRUE, results = 'hide')
```

## Επισήμανση πακέτων

```{r echo=TRUE, eval=TRUE, results='hide'}
library(tidyverse)
library(gplots)
```


## Εισαγωγή του αρχείου csv με τις καταγραφές των κυανοτοξινών στην περιοχή της Μεσογείου


```{r echo=TRUE, results='hide'}
med.toxins <- read.csv("../Data/Mediterranean_Cyanobacteria_toxins.csv")
colnames(med.toxins)[1] <- "A/A"
med.toxins
```


## Δημιουργία heatmap με βάση τις κυανοτοξίνες που παράγονται από τα διαφορετικά τάξα


```{r fig.height=6, fig.width=7, results='hide'}
med.heat.spe <- med.toxins %>% 
  select(Currentname, Country, Toxin) %>% 
  group_by(Currentname,Toxin) %>% 
  summarize(N = n_distinct("Currentname")) %>% 
  spread(Toxin, N, fill = 0) %>% 
  column_to_rownames("Currentname")
med.heat.spe <- as.matrix(med.heat.spe) ## Μετατροπή του dataframe σε matrix
med.heat.spe


##med.heat.scale.spe <- scale(med.heat.spe) 
png("../Results/heatmap.2.png", width=700, height=400)

map.spe <- heatmap.2(med.heat.spe, 
                     dendrogram = "both",
                     key = TRUE,
                     #keysize = 1.5,
                     cexRow = 0.7,
                     cexCol = 0.8,
                     margins = c(6,10),
                     srtRow=0, srtCol=45, offsetRow=-0.5, offsetCol=-0.5,
                     scale="none",
                     #distfun = dist,
                     sepcolor = "black",
                     col = c("#66c2a5", "#fc8d62"),
                     lwid = c(0.8,1),
                     lhei=c(0.05, 0.2 ),
                     labRow=as.expression(lapply(rownames(med.heat.spe), function(a) bquote(italic(.(a))))),
                     sepwidth = c(1,1.5),
                     trace = "none", 
                     density.info = "none"
                     )
dev.off()
```
