---
title: "year_barplot"
author: "Vica"
date: "10/24/2019"
output: html_document
---



```{r}
library(tidyverse)

```


```{r}
med <- read.csv("../Data/Med_cyano_list_20191204.csv")
med <- med %>% 
  filter(Med_border == "yes")
colnames(med)[1] <- "A/A"

```

```{r}
install.packages("ggThemeAssist")
library(ggThemeAssist)
```

#Barplot with records for each year

```{r}
#Convert the column Year to character
med$Year <- as.character(as.numeric(med$Year))

#Reorder variable Year using dplyr function
#mutate(name = fct_reorder(as.factor(Year), Count))
med$Title

year <- med %>% 
  select(Year, Title, Order) %>% 
  filter(Order != "") %>% 
  group_by(Year) %>% 
  summarize(Count = n())
year

  #mutate(Year_percent = Title)
year


year.barplot<- ggplot(year, aes(x=Year, y = Count, width = .7)) + geom_bar(stat = "identity", fill = "green", position = "identity") + theme_classic() + theme(axis.line = element_line(size = 0.2, 
    linetype = "solid"), axis.ticks = element_line(colour = "black"), 
    panel.grid.major = element_line(colour = NA), 
    panel.grid.minor = element_line(colour = NA), 
    axis.text = element_text(size = 12, colour = "black"), 
    panel.background = element_rect(fill = NA), 
    plot.background = element_rect(colour = NA), 
    legend.position = "none") +labs(x = NULL, y = NULL) + 
  theme(axis.text.x = element_text(angle = 90)) +
  theme(axis.text.x = element_text(vjust = 0.3))
year.barplot
ggsave("species_count_bar.png")

 
```

```{r}
title_count <- med %>% select(Year, Title) %>% 
  group_by(Year) %>% 
  summarize(N = n_distinct(Title))
title_count

title_count_bar <- ggplot(title_count, aes(x=Year, y = N, width = .7)) + geom_bar(stat = "identity", fill = "green", position = "identity") + theme_classic() + theme(axis.line = element_line(size = 0.2, 
    linetype = "solid"), axis.ticks = element_line(colour = "black"), 
    panel.grid.major = element_line(colour = NA), 
    panel.grid.minor = element_line(colour = NA), 
    axis.text = element_text(size = 12, colour = "black"), 
    panel.background = element_rect(fill = NA), 
    plot.background = element_rect(colour = NA), 
    legend.position = "none") +labs(x = NULL, y = NULL) + 
  theme(axis.text.x = element_text(angle = 90)) +
  theme(axis.text.x = element_text(vjust = 0.5))
title_count_bar
ggsave("title_count_bar.png")

```

